name: RyuZUTechnicalMagicCore
version: '${version}'
main: com.github.ryuzu.ryuzutechnicalmagiccore.RyuZUTechnicalMagicCore
api-version: '1.20'
authors: [Y_RyuZU]
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
    FastAsyncWorldEdit:
      load: BEFORE
      required: true
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: true
      join-classpath: true
    Oraxen:
      load: BEFORE
      required: true
      join-classpath: true
    MythicMobs:
      load: BEFORE
      required: true
      join-classpath: true
    ModelEngine:
      load: BEFORE
      required: true
      join-classpath: true
    UltimateAdvancementAPI:
      load: BEFORE
      required: true
      join-classpath: true
    WeaponMechanics:
      load: BEFORE
      required: true
      join-classpath: true
    Multiverse-Core:
      load: BEFORE
      required: true
      join-classpath: true